### ISSUE TITLE
does not build with the latest Alpine

### ISSUE THREAD

**Issue by rbucker** [neochrome/docker-bastion#1]
and trying to build with 3.1 generates many deprecation warnings.

```
In file included from /usr/include/fortify/sys/socket.h:23:0,
                 from ../includes.h:27,
                 from arc4random.c:27:
/usr/include/fortify/stdlib.h:36:1: error: 'realpath' undeclared here (not in a function)
 _FORTIFY_FN(realpath) char *realpath(const char *__p, char *__r)
 ^
In file included from /usr/include/openssl/crypto.h:120:0,
                 from /usr/include/openssl/bn.h:134,
                 from ../sshbuf.h:25,
                 from ../buffer.h:24,
                 from ../entropy.h:30,
                 from ../includes.h:174,
                 from arc4random.c:27:
/usr/include/fortify/stdlib.h: In function 'realpath':
/usr/include/fortify/stdlib.h:47:11: error: called object '__orig_realpath' is not a function or function pointer
   __ret = __orig_realpath(__p, __buf);
           ^
In file included from /usr/include/fortify/sys/socket.h:23:0,
                 from ../includes.h:27,
                 from arc4random.c:27:
/usr/include/fortify/stdlib.h:36:1: note: declared here
 _FORTIFY_FN(realpath) char *realpath(const char *__p, char *__r)
 ^
In file included from /usr/include/openssl/crypto.h:120:0,
                 from /usr/include/openssl/bn.h:134,
                 from ../sshbuf.h:25,
                 from ../buffer.h:24,
                 from ../entropy.h:30,
                 from ../includes.h:174,
                 from arc4random.c:27:
/usr/include/fortify/stdlib.h:57:9: error: called object '__orig_realpath' is not a function or function pointer
  return __orig_realpath(__p, __r);
         ^
In file included from /usr/include/fortify/sys/socket.h:23:0,
                 from ../includes.h:27,
                 from arc4random.c:27:
/usr/include/fortify/stdlib.h:36:1: note: declared here
 _FORTIFY_FN(realpath) char *realpath(const char *__p, char *__r)
```

**Comment by neochrome** [comment]
Hi,
Thanks for reporting. I'll have at look at it.

**Comment by neochrome** [comment]
I also see deprecation warnings when building locally (I added a Makefile to show how I do it), but the resulting image does seem to work. Still, I don't fancy those warnings and will continue looking into why those happens (need to brush up on my C skills).
Also please see the Dockerfile.example for a very minimalistic example on how to derive from the published images - that really should work, maybe you can verify that this is how you do it?

Best regards,
Johan

**Comment by rbucker** [comment]
I found the official makefile: http://git.alpinelinux.org/cgit/aports/tree/main/openssh/APKBUILD

I hope that helps.

**Comment by neochrome** [comment]
I updated to the latest version of alpine, edge (at the time of writing latest=3.6) which has pre-built binaries for openssh with pam support. So, in other words the latest image is now built with more up-to-date software :)

If you use the latest version of the image, please note that it works slightly different (see [README.md](../blob/f7d6d33eabbab43060ba12f457a84fd9c82dc291/README.md))
